// chromatique-studio/src/components/Footer.vue
<template>
  <footer class="w-full py-6 px-8 border-t border-[#C4C4C9] flex flex-col md:flex-row items-center justify-between text-xs font-mono text-[#55555D]">
    <span>© {{ currentYear }} 09 Labs • Built with Vue & Vite</span>
    <div class="flex gap-4 mt-2 md:mt-0">
      <a href="https://github.com/DeafGecko" target="_blank" rel="noopener" class="hover:text-[#111113] transition-colors">GitHub</a>
      <button @click="showPrivacy = true" class="hover:text-[#111113] transition-colors cursor-pointer">Privacy</button>
      <button @click="showTerms = true" class="hover:text-[#111113] transition-colors cursor-pointer">Terms</button>
    </div>
  </footer>

  <PrivacyPolicy :isOpen="showPrivacy" @close="showPrivacy = false" />
  <TermsOfService :isOpen="showTerms" @close="showTerms = false" />
</template>

<script setup>
import { ref } from 'vue'
import PrivacyPolicy from './PrivacyPolicy.vue'
import TermsOfService from './TermsOfService.vue'

const currentYear = new Date().getFullYear()
const showPrivacy = ref(false)
const showTerms = ref(false)
</script>

// swiss-ecommerce/components/Footer.tsx
import Link from 'next/link'

export function Footer() {
  return (
    <footer className="border-t border-[var(--color-border-light)] bg-[var(--color-background-alt)] mt-8 sm:mt-12">
      <div className="container mx-auto px-3 sm:px-4 py-6 sm:py-8">
        <div className="flex flex-col md:flex-row justify-between items-center gap-3 sm:gap-4">
          <span className="phase-name-p1 font-mono text-xs sm:text-sm">SWISS</span>
          <span className="phase-name-p2 inline-flex items-center gap-2">
            <span className="brand-icon inline-flex items-center justify-center w-6 h-6 bg-[#1a1a1a] text-white rounded-md flex-shrink-0" style={{ fontFamily: "'Cormorant Garamond', Georgia, serif", fontSize: '0.9rem', fontWeight: 400, lineHeight: '1' }}>M</span>
            <span className="brand-name text-sm font-semibold" style={{ fontFamily: "'Cormorant Garamond', Georgia, serif", letterSpacing: '0.04em', lineHeight: '1' }}>Monolith</span>
          </span>
          <nav className="flex flex-wrap justify-center gap-4 sm:gap-6 text-xs sm:text-sm">
            <a href="/about" className="hover:underline">About</a>
            <a href="/contact" className="hover:underline">Contact</a>
            <a href="/privacy" className="hover:underline">Privacy</a>
          </nav>
          <small className="text-[10px] sm:text-xs text-[var(--color-text-muted)]">
            Copyright © 2026 <a href="https://github.com/DeafGecko" target="_blank" rel="noopener noreferrer" className="hover:underline">09 Labs</a>
          </small>
        </div>
      </div>
    </footer>
  )
}
